from enum import Enum

class BackendKind(Enum):
    CPU: BackendKind
    METAL: BackendKind
    CUDA: BackendKind

class BackendFeature(Enum):
    GROWTH: BackendFeature
    CELL_CONTACTS: BackendFeature

def backend_available(backend: BackendKind) -> bool: ...

class Vec3:
    x: float
    y: float
    z: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...

class BackendInfo:
    @property
    def kind(self) -> BackendKind: ...
    @property
    def name(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def native(self) -> bool: ...

class CellInit:
    position: Vec3
    direction: Vec3
    length: float
    radius: float
    growth_rate: float
    cell_type: int

    def __init__(self) -> None: ...

class CellSnapshot:
    @property
    def id(self) -> int: ...
    @property
    def slot(self) -> int: ...
    @property
    def position(self) -> Vec3: ...
    @property
    def direction(self) -> Vec3: ...
    @property
    def length(self) -> float: ...
    @property
    def radius(self) -> float: ...
    @property
    def growth_rate(self) -> float: ...
    @property
    def cell_type(self) -> int: ...

class ContactParameters:
    activation_margin: float
    parallel_sine_threshold: float
    degeneracy_epsilon: float

    def __init__(self) -> None: ...

class CellContact:
    @property
    def first_id(self) -> int: ...
    @property
    def second_id(self) -> int: ...
    @property
    def first_slot(self) -> int: ...
    @property
    def second_slot(self) -> int: ...
    @property
    def ordinal(self) -> int: ...
    @property
    def point_on_first(self) -> Vec3: ...
    @property
    def normal(self) -> Vec3: ...
    @property
    def signed_separation(self) -> float: ...
    @property
    def weight(self) -> float: ...

class ContactGraph:
    @property
    def cell_count(self) -> int: ...
    @property
    def empty(self) -> bool: ...
    @property
    def contacts(self) -> list[CellContact]: ...
    def __len__(self) -> int: ...
    def incident_contact_indices(self, slot: int) -> list[int]: ...

class Simulation:
    def __init__(
        self,
        backend: BackendKind = BackendKind.CPU,
        reserved_capacity: int = 0,
    ) -> None: ...
    @property
    def backend_info(self) -> BackendInfo: ...
    def supports(self, feature: BackendFeature) -> bool: ...
    @property
    def time(self) -> float: ...
    @property
    def cell_count(self) -> int: ...
    def add_cell(self, cell: CellInit) -> int: ...
    def divide_equal(self, parent_id: int) -> tuple[int, int]: ...
    def step(self, dt: float) -> None: ...
    def find_cell_contacts(self, parameters: ContactParameters = ...) -> ContactGraph: ...
    def cell(self, id: int) -> CellSnapshot: ...
    def cells(self) -> list[CellSnapshot]: ...
    def lineage_parent(self, id: int) -> int | None: ...
    def validate(self) -> None: ...
