from enum import Enum

class BackendKind(Enum):
    CPU: BackendKind
    METAL: BackendKind
    CUDA: BackendKind

def backend_available(backend: BackendKind) -> bool: ...

class Vec3:
    x: float
    y: float
    z: float

    def __init__(self, x: float = 0.0, y: float = 0.0, z: float = 0.0) -> None: ...

class BackendInfo:
    @property
    def kind(self) -> BackendKind: ...
    @property
    def name(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def native(self) -> bool: ...

class CellInit:
    position: Vec3
    direction: Vec3
    length: float
    radius: float
    growth_rate: float
    cell_type: int

    def __init__(self) -> None: ...

class CellSnapshot:
    @property
    def id(self) -> int: ...
    @property
    def slot(self) -> int: ...
    @property
    def position(self) -> Vec3: ...
    @property
    def direction(self) -> Vec3: ...
    @property
    def length(self) -> float: ...
    @property
    def radius(self) -> float: ...
    @property
    def growth_rate(self) -> float: ...
    @property
    def cell_type(self) -> int: ...

class Simulation:
    def __init__(
        self,
        backend: BackendKind = BackendKind.CPU,
        reserved_capacity: int = 0,
    ) -> None: ...
    @property
    def backend_info(self) -> BackendInfo: ...
    @property
    def time(self) -> float: ...
    @property
    def cell_count(self) -> int: ...
    def add_cell(self, cell: CellInit) -> int: ...
    def divide_equal(self, parent_id: int) -> tuple[int, int]: ...
    def step(self, dt: float) -> None: ...
    def cell(self, id: int) -> CellSnapshot: ...
    def cells(self) -> list[CellSnapshot]: ...
    def lineage_parent(self, id: int) -> int | None: ...
    def validate(self) -> None: ...
